"""Add Service Registry

Revision ID: 83a8a97f180d
Revises: a9f728bf239d
Create Date: 2026-07-26 17:38:26.176688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a8a97f180d'
down_revision = 'a9f728bf239d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('execution_type', sa.String(length=30), nullable=False),
    sa.Column('module_path', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('method_name', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('http_method', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('ai_recommendations_zone_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'runs', ['run_id'], ['id'])
        batch_op.drop_column('zone_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_recommendations_zone_id_fkey'), 'zones', ['zone_id'], ['id'])
        batch_op.drop_column('run_id')

    op.drop_table('service_registry')
    # ### end Alembic commands ###
