"""Add sensor catalog

Revision ID: a9f728bf239d
Revises: aba77def17a8
Create Date: 2026-07-26 17:22:09.040285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f728bf239d'
down_revision = 'aba77def17a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('sensor_name', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_catalog')
    # ### end Alembic commands ###
