"""Add generic run model

Revision ID: aba77def17a8
Revises: 751250a418d6
Create Date: 2026-07-26 17:10:53.525365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba77def17a8'
down_revision = '751250a418d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(length=150), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'runs', ['run_id'], ['id'])

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'runs', ['run_id'], ['id'])

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('run_id')

    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('run_id')

    op.drop_table('runs')
    # ### end Alembic commands ###
